# Generated by Django 4.2.5 on 2023-10-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_list_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Bills',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AddField(
            model_name='product',
            name='bill',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='inventory.bill'),
            preserve_default=False,
        ),
    ]
